### ISSUE TITLE
currently broken install

### ISSUE THREAD

**Issue by mattdesl** [glslify/glslify-optimize#1]
the dependency has been removed from github:
https://github.com/kkaefer/glsl-optimizer

I would say fork the current glsl-optimize from aras-p since it should be node compatible (my native abstractions PR got merged a while back). It would be safer than relying on another Git repo which may change or be deleted at any time.

**Comment by hughsk** [comment]
Ah, that's no good! Checked http://github.com/mapbox/glify quickly and it looks like they've switched to using https://www.npmjs.org/package/mapbox-glsl-optimizer, which points to aras-p's repo.

I'm a little short on time right now so I can't fix just yet – you could send a PR and I'll merge/publish, or I'll update in the next day or two? :)

**Comment by mattdesl** [comment]
hmm, maybe depending on `mapbox-glsl-optimizer` would be safer than `aras-p/glsl-optimizer`?

**Comment by hughsk** [comment]
That's what I reckon :)

**Comment by hughsk** [comment]
Done! Let me know if it gives you any more trouble :)
